// <auto-generated />
namespace CMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GroupURI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GroupURI));
        
        string IMigrationMetadata.Id
        {
            get { return "201801311310384_GroupURI"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
